### ISSUE TITLE
Simplified getting-started error type

### ISSUE THREAD

**Issue by epage** [winnow-rs/winnow#103]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### winnow version

0.2.0

### Describe your use case

> the error typing in this library is a mess

https://hachyderm.io/@pearfalse@tech.lgbt/109767208540750093

### Describe the solution you'd like

Unsure

**Comment by martinohmann** [comment]
In #223 you mentioned maybe using `toml_edit`'s `ParserError` design.

Some thoughts:

In general I think the design is quite good and keeps track of enough information to build helpful error messages later on.

What I would change is to make the `ParserError` generic over the context and default to the builtin `Context` type, so users can choose their own, e.g.:

```rust
pub struct ParserError<I, C = Context> {
    input: I,
    context: Vec<C>,
    cause: Option<Box<dyn std::error::Error + Send + Sync + 'static>>,
}

impl ContextError<I, C> for ParserError<I, C> {
    fn add_context(mut self, _input: I, ctx: C) -> Self {
        self.context.push(ctx);
        self
    }
}
```

**Comment by epage** [comment]
Do you have a use case for custom context?

Being needs driven on making it generic allows us to better collect use cases and take them into account with the design.  This allows us to better do a cost/benefit analysis.  It could lead to the error being generic, to adding more to the current context, or some more fundamental design changes. 

I was also thinking of making the error store a `&[u8]` and implement the traits for `I: AsBStr`, making the error type focused on parsing text.  I suspect the needs for binary parsing are quite different and focusing on the text use case can let us improve the experience.

**Comment by martinohmann** [comment]
As a side note, I'm using some combinators like these to avoid littering the parser code with `.context()` calls everywhere when I'm expecting a certain char or literal:

```rust
pub(super) fn cut_char<'a>(c: char) -> impl Parser<Input<'a>, char, ParseError<Input<'a>>> {
    cut_err(c)
        .map(AsChar::as_char)
        .context(Context::Expected(Expected::Char(c)))
}

pub(super) fn cut_tag<'a>(
    tag: &'static str,
) -> impl Parser<Input<'a>, &'a [u8], ParseError<Input<'a>>> {
    cut_err(tag).context(Context::Expected(Expected::Literal(tag)))
}
```

I wonder if we could integrate something like this in a generic way to make attaching context a bit less verbose.

**Comment by martinohmann** [comment]
To answer your question: I don't have any use case for custom context yet. To me, having the option to create a char, string literal or description context is all I need.

**Comment by martinohmann** [comment]
Storing a `&[u8]` sounds like a good idea as it would make the error type a bit smaller, if one uses `Located` or `Stateful` as input, and that in turn could improve performance here and there.
