### ISSUE TITLE
Tutorial headers dont fit descriptipn

### ISSUE THREAD

**Issue by IchBinMatz** [winnow-rs/winnow#200]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### rust version

none

### winnow version

0.3.2

### Minimal reproducible code

```rust
```

### Steps to reproduce the bug with the above code

no bugs in code

### Actual Behaviour

In the tutorial from chapter five on til the end. The Title of the section starts with a different number.

Am I missing a step (where is the real section 5) or is it just wrong numbering ?

![grafik](https://user-images.githubusercontent.com/71331385/221358078-c1a40e1b-17e9-4ec6-b526-3161df864307.png)

### Expected Behaviour

https://docs.rs/winnow/latest/winnow/_tutorial/chapter_5/index.html

should display [Chapter 5: Repetition](https://docs.rs/winnow/latest/winnow/_tutorial/chapter_5/index.html#chapter-6-repetition)

### Additional Context

There is no GitHub Issue Template for fixed in the doc. Is this even the right place for that? sorry, it's my first time contributing to Open Source.

**Comment by epage** [comment]
Thanks for reporting that!
