### ISSUE TITLE
Increasing the MSVR should not be done in a patch version

### ISSUE THREAD

**Issue by emabee** [winnow-rs/winnow#248]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### winnow version

0.4.2

### Describe your use case

With version 0.4.2, the MSVR was raised to 1.64.0. 
Such a change creates issues for all depending libs, since their MSVR by that is force-raised to 1.64.0, too, without any explicit change.

### Describe the solution you'd like

I think it would be cleaner to do MSVR updates in minor or major version bumps only!

**Comment by epage** [comment]
> With version 0.4.2, the MSVR was raised to 1.64.0.

Yes, I've been trying to keep the MSRV lower on this project than I normally do on my other projects (generally current + 2) but there was a const-generics feature I needed from 1.64.0 as part of my work to prepare for v0.5.0.  To make upgrading to v0.5.0 easier and to minimize the time going dark between v0.4.x and v0.5.0, I try to do as much work as possible in stable releases by creating new APIs, and deprecating the old ones..

> Such a change creates issues for all depending libs, since their MSVR by that is force-raised to 1.64.0, too, without any explicit change.

No, it doesn't.  Your MSRV is only dependent on your version requirements, not the latest version of all of your dependencies.  Granted, this requires fiddling with a committed `Cargo.lock` file to verify your MSRV until rust-lang/cargo#9930 is implemented and stablized (we are working on it)

> I think it would be cleaner to do MSVR updates in minor or major version bumps only!

There are two aspects here.

The first is that winnow is at `0.x.y`.  Cargo's variant of semver treats the terms "major", "minor", and "patch" as relative.  
- `major.,minor.patch`
- `0.major.minor`
- `0.0.major`

So we can't distinguish between minor and patch releases at this time.

As for being a breaking change, there were people more actively advocating for that within the community but support for that has dwindled and people generally recognize it as a "minor incompatibility", like deprecations, which falls in the "minor" category
- Being over eager for bumping major versions can cause a lot more churn within the community, both from the more manual upgrade process and from keeping common versions in sync
- Being over eager for bumping major versions will increase build times as it increases the likelihood of having duplicates of a dependency in your dependency tree

This is analogous to rust requiring new versions of glibc or Android NDK.  Rust is still on 1.x.y and not 5.x.y from having made these changes
