### ISSUE TITLE
Add something to the README.md to explain the difference to nom (and possibly other parser combinator crates)

### ISSUE THREAD

**Issue by sdroege** [winnow-rs/winnow#249]
The README.md seems to hint that this is based on nom, so it would be useful to also write a paragraph or two how it is different from nom.

Similarly there are a lot of parser combinator crates for Rust now and a short comparison with the main ones would be useful.

**Comment by epage** [comment]
Currently this is covered in the [docs.rs Special Topic: Why?](https://docs.rs/winnow/latest/winnow/_topic/why/index.html).  I could see linking out to that from the README
