### ISSUE TITLE
Unknown start of token: \u{0} | 0.5.17 -> 0.5.18 Bug/Breaking Change?

### ISSUE THREAD

**Issue by ShayBox** [winnow-rs/winnow#361]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### rust version

rustc 1.73.0 (cc66ad468 2023-10-03)

### winnow version

0.5.18

### Minimal reproducible code

```rust
fn main() {}
```

### Steps to reproduce the bug with the above code

`cargo add winnow`  
`cargo build`

### Actual Behaviour

```
error: unknown start of token: \u{0}
 --> C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winnow-0.5.18\src\lib.rs:1:1
  |
1.|.
  | ^
  |
  = help: source files must contain UTF-8 encoded text, unexpected null bytes might occur when a different encoding is used
  = note: character appears 7744 more times

error: could not compile `winnow` (lib) due to previous error
```

### Expected Behaviour

It should compile successfully.

### Additional Context

I use `human-panic` in my project, which uses `toml`, which uses `toml_edit`, which uses `winnow`.  

When I updated my project it failed to compile, but works if I revert back to `0.5.15`.  

~~I haven't tried `0.5.17` but~~ I did try `0.5.18` in a new project with no code or other dependencies and it fails to compile.

EDIT: I tried `0.5.17` which works, it's just `0.5.18` which doesn't compile.

**Comment by epage** [comment]
Looking at the [diff between 0.5.17 and 0.5.18](https://diff.rs/winnow/0.5.17/0.5.18/src/lib.rs), I'm not seeing this.

I also went into `human-panic`, ran `cargo update -p winnow`, did a build, and it worked.

My best guess is the extraction of `winnow` 0.5.18 got interrupted, corrupting the file.  If you delete `C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winnow-0.5.18`, I assume it will work again.

**Comment by ShayBox** [comment]
Oh yeah that was it, I forgot my computer had blue-screened the first time I tried to cargo update, thanks :+1:
