### ISSUE TITLE
When do we need infinite loop checks?

### ISSUE THREAD

**Issue by vwkd** [winnow-rs/winnow#365]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### rust version

rustc 1.72.1

### winnow version

v0.5.18

### Minimal reproducible code

While trying to implement a `separated` parser that accepts a range in #362, I found some [combinator parsers](https://github.com/winnow-rs/winnow/blob/main/src/combinator/multi.rs) have "infinite loop checks" like this

```rs
if input.eof_offset() == len {
    return Err(ErrMode::assert(i, "sep parsers must always consume"));
}
```

It would be good to know if and when they are necessary. For example

- are they only necessary in infinite loops or also in finite loops?
- are they necessary for each parser when there are multiple parsers, e.g. element parser and separator parser in `separated`

**Comment by epage** [comment]
They are needed to prevent infinite loops.  The odd situation is when a ranged combinator can sometimes be at risk to an infinite loop and sometimes not.  I think consistency is better as it makes the behavior clearer (no weird caveats in documentation).

`repeat(5, ...)` does not implement the check.  I believe `repeat(1..5, ...)` does implement the check.

**Comment by vwkd** [comment]
Expanding on my initial questions:

- Are the checks needed for `separated` at all assuming the element parser and separator parser are different (otherwise it would just be like a `repeat`)[^1]?
- Are the checks necessary for each parser when there are multiple parsers, e.g. element parser and separator parser in separated
- Are the checks also necessary in finite loops?

[^1]: Maybe we should verify the element parser and separator parser passed to `separated` are actually different…)

**Comment by epage** [comment]
Yes, the checks are needed for `separated`.  If you have two parsers that can each sometimes match an empty string, there could be cases where they both match an empty string and you get in an infinite loop

We only need the check for sep or regular parser.  We don't need it for both.  Its very common to have an empty element between separators, so we bias towards that in the implementation.  See also #325.

I spoke to the checks for finite ranges earlier.

**Comment by vwkd** [comment]
Makes sense.

Regarding the finite loops, as you mentioned the checks are currently only present for `repeat_m_n_` but not `repeat_n_`. Meanwhile #362 adds them on both `separated_n_` and `separated_m_n_`. To make it consistent, it seems we should either also add them to `repeat_n_` or remove them from `separated_n_`.

**Comment by epage** [comment]
I'd propose, on next breaking release, add them to `repeat_n_`

**Comment by vwkd** [comment]
I'd actually push back here and suggest removing them from `separated_n_`, since this is a finite loop that can't end up in an infinite loop.

**Comment by epage** [comment]
I gave my reason earlier.  Could you speak to that?

**Comment by vwkd** [comment]
> The odd situation is when a ranged combinator can sometimes be at risk to an infinite loop and sometimes not.

I don't understand in which situation a `for _ in 0..n {..}` loop in an `_n_` parser could end up in an infinite loop.

The `_m_n_` parser can end up in an infinite loop, since apart from bounded ranges it also runs on unbounded ranges[^1] like `2..`.

[^1]: Although the implementation ultimately bounds the range to `usize::max`, not sure why.

**Comment by epage** [comment]
I'm speaking from the users perspective. They just see a `repeat` or `separated` documented. Having the assert be documented to always hit works better than making it dependent also on the range passed in

**Comment by vwkd** [comment]
Seems like a good argument. Opened #368 to add the check to `repeat`.

**Comment by 9999years** [comment]
I'm having an issue, I'm not sure if this is related, where I want to parse lines of text, but I also want to treat end-of-file as a newline. (Some naughty text editors [like VS Code](https://stackoverflow.com/questions/44704968/visual-studio-code-insert-newline-at-the-end-of-files) don't write a newline at the end of the file by default.)

My current attempt looks like this and seems to always trigger the infinite loop check:

```
terminated(not_line_ending, alt((line_ending, eof)))
```
