### ISSUE TITLE
Add a non-consuming combinator that returns `()`

### ISSUE THREAD

**Issue by epage** [winnow-rs/winnow#399]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### winnow version

0.5.30

### Describe your use case

`success` only handles the equivalent of `Parser::value` but there is also `Parser::void`, `Parser::default_value` (#398).

### Describe the solution you'd like

[`chumsky::primitive::empty`](https://docs.rs/chumsky/latest/chumsky/primitive/fn.empty.html) would be nice

The main question is in naming
- `empty`: conveys what is done for parsing
- `success` reads nicely for longer `alt`s
- `void` ... too focused on the output and not the grammar

### Additional Context

Split out of #82

**Comment by baoyachi** [comment]
#### Provide a few name references：
- noop or no_op: representing 'no operation,' meaning it does not produce any effect when executed.
- pass
- skip
- do_nothing
