### ISSUE TITLE
Can weights be assigned to the combinators within alt 

### ISSUE THREAD

**Issue by baoyachi** [winnow-rs/winnow#445]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### winnow version

0.5.34

### Describe your use case

"alt((A, B, C))" signifies that one of multiple combinators will be matched. Can weights be assigned to the combinators within alt so that those with higher hit rates are prioritized for parsing, rather than always parsing them in sequential order?

### Describe the solution you'd like

no

**Comment by epage** [comment]
Could you describe the use case for why an explicit weight would be use rather than the implicit one based on the ordering?

**Comment by epage** [comment]
Without extra context, I'm going to go ahead and close this.  If there is a reason for us to re-evaluate, let us know!
