### ISSUE TITLE
"recognize" meaning is non-obvious

### ISSUE THREAD

**Issue by epage** [winnow-rs/winnow#488]
We have `Parser::recognize`, `Parser::with_recognize`, and use of "recognize" in various parsers (especially `token`)

The leap from the word and its meaning is unclear

See also #95

**Comment by epage** [comment]
In reading through the docs, I realized I would sometimes insert the word "capture" which I think works well as a parallel to regex.

**Comment by baoyachi** [comment]
Why not `concat`.

Related links: https://doc.rust-lang.org/stable/std/macro.concat.html

**Comment by epage** [comment]
For now at least, I lean towards `take` / `with_taken`
