### ISSUE TITLE
About &str input  using method  split at_checked instead of split_at method to avoid panic

### ISSUE THREAD

**Issue by baoyachi** [winnow-rs/winnow#540]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### rust version

rustc 1.78.0 (9b00956e5 2024-04-29)

### winnow version

0.6.13

### Minimal reproducible code

the core code in winnow:
https://github.com/winnow-rs/winnow/blob/e826529f4c4cca974f27fde5a85d78ee2292fab1/src/stream/mod.rs#L832-L836
```diff
fn next_slice(&mut self, offset: usize) -> Self::Slice { 
+     let (slice, next) = self.split_at(offset); 
     *self = next; 
     slice 
 } 

```

### Steps to reproduce the bug with the above code

When the received input parameter is passed in from outside, it is not a valid utf-8, which can cause panic when calling the [split_at](https://doc.rust-lang.org/std/primitive.slice.html#method.split_at) method. Perhaps using the [split_at_checked](https://doc.rust-lang.org/std/primitive.slice.html#method.split_at_checked) method can avoid this problem from happening.

### Actual Behaviour

about str split_at document :https://doc.rust-lang.org/std/primitive.slice.html#method.split_at

### Expected Behaviour

using the [split_at_checked](https://doc.rust-lang.org/std/primitive.slice.html#method.split_at_checked) method can avoid this problem from happening.

**Comment by epage** [comment]
[Stream::next_slice](https://docs.rs/winnow/latest/winnow/stream/trait.Stream.html#tymethod.next_slice) is documented to require a valid offset.

Could you go into your use case where are you passing in an invalid offset?  What would be the correct course of action in `next_slice` failing in a parser?
