### ISSUE TITLE
`alt`, `opt` but with resetting state

### ISSUE THREAD

**Issue by g-plane** [winnow-rs/winnow#549]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### winnow version

0.6.8

### Describe your use case

Currently we have `alt` and `opt` which can try next parser if previous parser failed, but it doesn't reset state when using with `Stateful`. Are there any ways to do something like `alt` and `opt` but can reset state?

### Describe the solution you'd like

Provide an additional API like `alt` and `opt`. Usages should be same.

**Comment by epage** [comment]
alt, opt, repeat, etc can be nested arbitrarily deep.  This would quickly be quite expensive to track that state to allow rolling back.  The type was more intended for cases when you'd have applied `cut_err`.

You are free to develop your own wrapper and combinators on a `trait ParaerStateExt` for yourself and to test the waters for how much need there is for this but I think I am instead going to close this.  If there is a reason we should re-evaluate, let us know!
