### ISSUE TITLE
Return `&char` when parsing `char`

### ISSUE THREAD

**Issue by Caellian** [winnow-rs/winnow#608]
### Please complete the following tasks

- [x] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### winnow version

0.6.20

### Use case

`'0'.parse_next(input)?` returns a `char` value. I'd like to store `&'s char` in order to store information about token position in input.

For instance, `syn` can't generate errors on some tokens because their `Span` is erased, this is that same problem. After parsing is complete, if I want to highlight '.' symbol in a float in some error message (e.g. "because of '.' in 2.464, expected float"), I need to do so by extrapolating child token position from parent token.

### Solution

`'0'.parse_next(input)?` should return `&'s char` instead. I know that the crate provides parsing errors, but having the actual token position is very useful.

So returned value should be some utf8-compatible version of:
```rust
pub fn first_char(input: &str) -> &char {
    unsafe {
        let c = core::ptr::addr_of!(input.as_bytes()[0]);
        let c = c as *const char;
        c.as_ref().unwrap_unchecked()
    }
}
```

**Comment by Caellian** [comment]
Closing due to #232.

**Comment by Caellian** [comment]
Ok, nvm, that's only possible for ASCII because UTF8 is variable width.

**Comment by epage** [comment]
Alternatively, you could
- Create a custom stream where tokens are `&str`
- Use `parser.take()` to capture the spans for what is being parsed

**Comment by Caellian** [comment]
Thanks for feedback.

I believe `take` is what I was looking for.
