### ISSUE TITLE
Doc suggestion for migrating nom -> winnow

### ISSUE THREAD

**Issue by Ben-PH** [winnow-rs/winnow#612]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### winnow version

0.3

### Describe your use case

Migrating from nom to winnow ran into trouble here:

```rust
        let (_input, param_values) = many_m_n(
```

The `param_values` could not be inferred by the type system. I managed to find the solution:

```rust
        let (_input, param_values): (_, BTreeMap<&str, &str>) = many_m_n(
```

...but took a long time to get there. 

### Describe the solution you'd like

I'm not exactly sure _exactly_ what to ask for here. My best guess is a section in the migration guide that covers these kinds of edge cases: "many_m_n has some type ambiguity. Check the accumulator trait for more information", or something like that.

**Comment by epage** [comment]
I have a proposed improvement in #613
