### ISSUE TITLE
An easier way to discard fields in a tuple

### ISSUE THREAD

**Issue by epage** [winnow-rs/winnow#82]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### winnow version

0.2.0

### Describe your use case

Some sequences of parsers (via tuples) become long and it can be a mess to deal with the resulting values as some fields are there for parsing purposes and don't matter.  Judicious use of `preceded` and `terminated` help but that also makes it harder to read.

Ideally, I could also say to `cut` in the middle without creating a new tuple.

### Describe the solution you'd like

A macro for populating a struct
- https://docs.rs/combine/latest/combine/macro.struct_parser.html
- https://crates.io/crates/nom-derive
- https://crates.io/crates/nom-fields

**Comment by epage** [comment]
Is this worth it?  Somehow I never use this existed in `combine` and so I never used it.  If I were, the hassle with it is I have to go and write a struct (at least in `combine`s version) which negates the benefits.

**Comment by epage** [comment]
combine's `struct_parser` supports fields with `_` as the name so they are never written to the struct:
```rust

    let mut parser = struct_parser!{
        Field {
            name: many(letter()),
            // `_` fields are ignored when building the struct
            _: spaced(b':'),
            value: many(letter()),
            _: spaced(b':'),
            point: struct_parser!(Point(num(), _: spaced(b','), num())),
        }
    };
```

**Comment by epage** [comment]
`nom-derive` doesn't use `tuple` to sequence but instead parses more imperatively,  allowing you to refer back to previous fields
```rust
#[derive(Debug, PartialEq, NomBE)]
pub struct NtpExtension<'a> {
    pub field_type: u16,
    pub length: u16,
    #[nom(Parse = "take(length)")]
    pub value: &'a [u8],
    /*padding*/
}
```

**Comment by epage** [comment]
`nom-derive` also has anonymous fields that can be referenced later.  However, they do this by directly injecting rust code.  I have not been able to think of a better solution though
```rust
/// An NTP version 3 packet
#[derive(Debug, PartialEq, NomBE)]
pub struct NtpV3Packet<'a> {
    #[nom(PreExec = "let (i, b0) = be_u8(i)?;")]
    #[nom(Value(b0 >> 6))]
    pub li: u8,
    #[nom(Value((b0 >> 3) & 0b111))]
    pub version: u8,
    #[nom(Value(NtpMode(b0 & 0b111)))]
    pub mode: NtpMode,
    pub stratum: u8,
    pub poll: i8,
    pub precision: i8,
    pub root_delay: u32,
    pub root_dispersion: u32,
    pub ref_id: u32,
    pub ts_ref: u64,
    pub ts_orig: u64,
    pub ts_recv: u64,
    pub ts_xmit: u64,

    #[nom(Parse = "opt(complete(take(12usize)))")]
    pub authenticator: Option<&'a [u8]>,
}
```

**Comment by epage** [comment]
I think both can be useful, depending on what best expresses what the user is doing

**Comment by epage** [comment]
Started on #238 but not quite getting the macro right.  Taking a break in case I just need a fresh set of eyes (or in case someone else spots the problem)

**Comment by epage** [comment]
I hit a snag for #238.  I got `seq!(Struct {})` working but can't get tuples or tuple structs to work without just making them tuples and using `map` to drop elements.  That would hut #237.  The issue is that I can't create identifiers to store the tuple elements in inbetween parsing and structuring of the tuple.  I could if we did this using a proc-macro but I was also hoping for this to be lighter weight than a proc macro.

**Comment by martinohmann** [comment]
Would it also be possible to support populating only a fraction of the struct's fields and `Default::default()` the rest via `seq!`?

E.g. something like:

```rust
    seq!( Request {
        method: take_while1(is_token),
        _: take_while1(is_space),
        uri: take_while1(is_not_space),
        _: take_while1(is_space),
        version: http_version,
        _: line_ending,
        some_other_field: Default::default(),
    })
    .parse_next(input)
```

My use case is that most of the structs emitted by my `hcl-edit` parser have the `decor` and `span` fields that are initialized with defaults and get populated later via another combinator. For example, I'm adding decor and span information via special `decorated` and `spanned` combinators that are used like `decorated(ws, parse_struct_implementing_decorate_trait, ws)`: https://github.com/martinohmann/hcl-rs/blob/b29bdb540ad4271a2b6bbc121614b1045a5081f2/crates/hcl-edit/src/parser/repr.rs#L8-L36

The current implementation of `seq!` wouldn't work for my use case.

**Comment by martinohmann** [comment]
I just realized that this does not need special-casing inside the `seq!` macro, so you can diregard my previous comment. Default values can be supported by something like this:

```rust
    #[inline(always)]
    fn default_value<I, O, E>(input: I) -> IResult<I, O, E>
    where
        O: Default,
    {
        Ok((input, Default::default()))
    }

    seq!( Request {
        method: take_while1(is_token),
        _: take_while1(is_space),
        uri: take_while1(is_not_space),
        _: take_while1(is_space),
        version: http_version,
        _: line_ending,
        some_other_field: default_value,
    })
    .parse_next(input)
```

**Comment by epage** [comment]
You could also use the [`success`](https://docs.rs/winnow/latest/winnow/combinator/fn.success.html) parser for this.  Might be reasonable to have a version for a default value, just naming is an issue.  Non-nom parsers call `success`, `value`.  It'd be easy if we could call them `value` and `default_value`.  I've avoided that because it might be confusing with `Parser::value` (which nom calls `value` and is a hard name conflict)

**Comment by martinohmann** [comment]
Right, totally forgot about `success`, thanks! 👍

**Comment by epage** [comment]
Interesting, `chumsky` calls it `empty` and its Output is `()`, requiring you to do `empty.value(...)`.  The nice thing about `empty` is you can use whatever `Parser` combinators you want but `success`s behavior is most likely what you want, so its more boiler plate

**Comment by epage** [comment]
#398 adds `Parser::default_value`.

Created #399 for tracking a new combinator so we can do `empty.default_value()`
